"""Clinical treatment plan report — JSON and a printable text/HTML summary.

WHO THIS IS FOR. A clinician who has to decide whether to thermoform this plan,
and who was not sitting at the workstation when it was made. It therefore leads
with what is uncertain rather than burying it: which teeth need review, which
movements are outside the planning envelope, and which checks did not run.

WHAT IT DELIBERATELY DOES NOT CONTAIN. No patient name, date of birth, or any
other identifier. The case is referenced by its opaque id and the clinician's
own free-text label — which the UI is told not to use for a name, and which this
module does not attempt to police because a scrubber that misses one is worse
than a stated rule.

WHY NOT A PDF. Producing one needs reportlab or weasyprint, and adding a
dependency to make a document prettier is a poor trade when the browser prints
HTML perfectly well. `write_html()` produces something that prints to PDF with
Ctrl+P and carries the same content as the JSON, which is the machine-readable
record. If a true PDF pipeline is wanted later it should read the JSON, not
re-derive any of this.
"""
from __future__ import annotations

import html
import json
import os
import time

import clinical_safety
import domain

DISCLAIMER = ("Generated by Project Aligner Workstation. For professional orthodontic "
              "clinician review only. Requires clinical verification prior to "
              "thermoforming.")

FIELD_LABELS = [
    ("tip_deg", "Tip", "deg"), ("torque_deg", "Torque", "deg"),
    ("rotation_deg", "Rotation", "deg"), ("d_md", "Mesial/Distal", "mm"),
    ("d_bl", "Buccal/Lingual", "mm"), ("d_oa", "Intrusion/Extrusion", "mm"),
]


def build(case: domain.Case, space_analysis: dict | None = None,
          attachments: list | None = None,
          segmentation_review: dict | None = None) -> dict:
    """Assemble the report. Pure data — nothing here touches the filesystem."""
    teeth = case.all_teeth()
    stages = case.stage_count()

    safety = clinical_safety.assess_case(
        [{"tooth_id": t.tooth_id, "fdi": t.fdi,
          "prescription": {k: getattr(t.prescription, k) for k, _, _ in FIELD_LABELS}}
         for t in teeth], stages)
    by_id = {r["tooth_id"]: r for r in safety["teeth"]}

    rows = []
    for t in sorted(teeth, key=lambda x: (x.fdi is None, x.fdi or 0)):
        s = by_id.get(t.tooth_id, {})
        rows.append({
            "tooth_id": t.tooth_id,
            "fdi": t.fdi,
            "tooth_class": t.tooth_class,
            "arch": t.arch,
            "movements": {k: round(getattr(t.prescription, k), 3) for k, _, _ in FIELD_LABELS},
            "root_length_mm": t.root_length_mm,
            "root_matches_fdi": t.root_length_matches_fdi(),
            "c_res": t.c_res,
            "stages": t.prescription.stages(),
            "safety_status": s.get("status"),
            "safety_findings": s.get("findings", []),
            "review_state": t.review,
        })

    # Tray schedule. Deliberately without dates: the wear interval is the
    # clinician's decision and the software does not know it.
    schedule = [{"stage": k,
                 "is_start": k == 0,
                 "is_final": k == stages,
                 "teeth_moving": sum(1 for t in teeth
                                     if t.prescription.stages() >= k and k > 0)}
                for k in range(stages + 1)]

    ipr = []
    if space_analysis:
        for c in (space_analysis.get("interproximal", {}) or {}).get("contacts", []):
            if c.get("state") == "CONTACT":
                ipr.append({
                    "contact": c.get("pair"), "fdi": c.get("fdi"),
                    "measured_gap_mm": c.get("gap_mm"),
                    "note": c.get("detail"),
                    # The software measures a gap. It does not prescribe how much
                    # enamel to remove, and saying so on every row is the point.
                    "reduction_mm": None,
                    "caution": "MEASURED GAP, NOT A PRESCRIPTION. Enamel reduction is a "
                               "clinical decision; this is a vertex-to-vertex minimum "
                               "which overestimates the true gap.",
                })

    unreviewed = [r for r in rows if r["review_state"] == "unreviewed"]
    bad_root = [r for r in rows if r["root_matches_fdi"] is False]

    return {
        "generated": time.time(),
        "generated_iso": time.strftime("%Y-%m-%d %H:%M", time.localtime()),
        "case_reference": case.case_id,
        "case_label": case.label,
        "schema_version": case.schema_version,
        "arches": sorted(case.arches),
        "tooth_count": len(teeth),
        "stage_count": stages,
        "binding_teeth": case.binding_teeth(),
        "movement_table": rows,
        "tray_schedule": schedule,
        "ipr_table": ipr,
        "attachments": attachments or [],
        "safety": safety,
        "segmentation_review": segmentation_review,
        "outstanding": {
            "teeth_unreviewed": [r["fdi"] or r["tooth_id"] for r in unreviewed],
            "root_length_mismatches": [r["fdi"] for r in bad_root],
            "antagonist_checked": bool(len(case.arches) > 1),
        },
        "audit_summary": case.trail().summary(),
        "disclaimer": DISCLAIMER,
        "phi": "No patient identifier is included. The case is referenced by an opaque "
               "id and the clinician's own label.",
    }


def write_json(report: dict, path: str) -> str:
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        json.dump(report, fh, indent=2, default=str)
    os.replace(tmp, path)
    return os.path.abspath(path)


def _chip(status):
    colour = {"GREEN": "#2f7d32", "YELLOW": "#b26a00", "RED": "#b3261e"}.get(status, "#5f6368")
    return f'<span style="background:{colour};color:#fff;padding:1px 7px;border-radius:9px;font-size:11px">{html.escape(str(status))}</span>'


def write_html(report: dict, path: str) -> str:
    """A printable summary. Ctrl+P gives a PDF without a new dependency."""
    r = report
    out = [
        "<!doctype html><meta charset='utf-8'>",
        "<title>Treatment Plan — {}</title>".format(html.escape(r["case_reference"])),
        "<style>body{font:13px/1.5 system-ui,sans-serif;margin:32px;color:#202124;max-width:1000px}"
        "h1{font-size:20px;margin:0 0 2px}h2{font-size:14px;margin:26px 0 8px;"
        "border-bottom:1px solid #dadce0;padding-bottom:4px}"
        "table{border-collapse:collapse;width:100%;font-size:12px}"
        "th,td{border:1px solid #dadce0;padding:5px 7px;text-align:right}"
        "th{background:#f1f3f4;text-align:center}td:first-child,th:first-child{text-align:left}"
        ".warn{background:#fff4e5}.bad{background:#fce8e6}"
        ".note{color:#5f6368;font-size:11px}"
        ".disc{margin-top:28px;padding:11px 13px;border:2px solid #b3261e;"
        "border-radius:5px;background:#fce8e6;font-weight:600}</style>",
        f"<h1>Treatment Plan</h1>",
        f"<div class='note'>Case {html.escape(r['case_reference'])}"
        + (f" &middot; {html.escape(r['case_label'])}" if r["case_label"] else "")
        + f" &middot; generated {html.escape(r['generated_iso'])}"
        + f" &middot; {r['tooth_count']} teeth &middot; {r['stage_count']} stages"
        + f" &middot; overall {_chip(r['safety']['overall'])}</div>",
        f"<p>{html.escape(r['safety']['summary'])}</p>",
    ]

    out.append("<h2>Tooth-by-tooth movement</h2><table><tr><th>Tooth</th>"
               + "".join(f"<th>{html.escape(lbl)}<br><span class='note'>{u}</span></th>"
                         for _, lbl, u in FIELD_LABELS)
               + "<th>Stages</th><th>Status</th></tr>")
    for row in r["movement_table"]:
        cls = ("bad" if row["safety_status"] == "RED"
               else "warn" if row["safety_status"] == "YELLOW" else "")
        name = f"FDI {row['fdi']}" if row["fdi"] else row["tooth_id"][:8]
        if row["tooth_class"]:
            name += f" <span class='note'>({html.escape(row['tooth_class'])})</span>"
        out.append(f"<tr class='{cls}'><td>{name}</td>"
                   + "".join(f"<td>{row['movements'][k]:+.2f}</td>" for k, _, _ in FIELD_LABELS)
                   + f"<td>{row['stages']}</td><td>{_chip(row['safety_status'])}</td></tr>")
    out.append("</table>")

    findings = [(row, f) for row in r["movement_table"] for f in row["safety_findings"]]
    if findings:
        out.append("<h2>Safety findings</h2><table><tr><th>Tooth</th><th>Level</th>"
                   "<th>Finding</th><th>Threshold</th></tr>")
        for row, f in findings:
            t = f.get("threshold") or {}
            who = f"FDI {row['fdi']}" if row["fdi"] else row["tooth_id"][:8]
            out.append(
                f"<tr><td>{html.escape(who)}</td>"
                f"<td>{_chip(f['level'])}</td>"
                f"<td style='text-align:left'>{html.escape(f['message'])}</td>"
                f"<td>{t.get('value','')} {html.escape(str(t.get('units','')))}"
                f"<br><span class='note'>{html.escape(str(t.get('basis','')))}</span>"
                f"</td></tr>")
        out.append("</table>")

    if r["ipr_table"]:
        out.append("<h2>Interproximal contacts</h2>"
                   "<p class='note'>Measured gaps, not prescriptions. Enamel reduction "
                   "is a clinical decision.</p>"
                   "<table><tr><th>Contact</th><th>Measured gap (mm)</th><th>Note</th></tr>")
        for i in r["ipr_table"]:
            out.append(f"<tr><td>{html.escape(str(i['contact']))}</td>"
                       f"<td>{i['measured_gap_mm']}</td>"
                       f"<td style='text-align:left' class='note'>{html.escape(str(i['note']))}</td></tr>")
        out.append("</table>")

    if r["attachments"]:
        out.append("<h2>Attachments</h2><table><tr><th>Tooth</th><th>Type</th>"
                   "<th>Dimensions (mm)</th><th>Purpose</th></tr>")
        for a in r["attachments"]:
            d = a.get("dimensions_mm", {})
            out.append(f"<tr><td>{html.escape(str(a.get('fdi') or a.get('tooth_id','')))}</td>"
                       f"<td>{html.escape(str(a.get('shape','')))}</td>"
                       f"<td>{d.get('md','')} x {d.get('oa','')} x {d.get('bl','')}</td>"
                       f"<td style='text-align:left' class='note'>{html.escape(str(a.get('purpose','')))}</td></tr>")
        out.append("</table>")

    o = r["outstanding"]
    out.append("<h2>Outstanding before thermoforming</h2><ul>")
    out.append(f"<li>Teeth not yet reviewed: {o['teeth_unreviewed'] or 'none'}</li>")
    out.append(f"<li>Root length inconsistent with FDI: {o['root_length_mismatches'] or 'none'}</li>")
    out.append("<li>Antagonist check: "
               + ("performed against the opposing arch" if o["antagonist_checked"]
                  else "<b>NOT PERFORMED</b> — no opposing arch loaded. This is not a "
                       "finding of no interference.") + "</li>")
    out.append("</ul>")

    out.append(f"<p class='note'>{html.escape(r['safety']['limitation'])}</p>")
    out.append(f"<div class='disc'>{html.escape(r['disclaimer'])}</div>")

    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))
    os.replace(tmp, path)
    return os.path.abspath(path)
